### ISSUE TITLE
Java runtime bundle contains unnecessary code

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/validation#67]
We, probably need to to ProGuard it. 11MB for such a thing is way too much.

**Comment by armiol** [comment]
We have a complete control over what we put into this JAR. So instead of cutting it with ProGuard at a later stage, we can just not put redundant things into it in the first place. We already filter out some things like Gradle classes, at a time of assembly. 

Also, 11 MB seems not too much, if you ask me. That's the whole Spine framework (base, time, base-types, core, client, server) along with its dependencies.

In any case, current contents should be analyzed and tested in a non-Spine-library (!) project — otherwise the picture won't be clear. In this way, we'll be able to tell whether the types we carry on board are redundant or they are really needed.

**Comment by alexander-yevsyukov** [comment]
Per #166, we don't need this artifact at all.
